name: Isolated Docker Compose Tests

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Get IP Address
      id: get-ip
      run: echo "OPENIM_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

    - name: Get OpenIM Data DIR
      id: get-dir
      run: echo "DATA_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Run Docker Compose
      run: |
        docker-compose up -d
        docker-compose ps

    - name: Test OpenIM Server
      run: |
        sleep 30
        docker-compose logs --tail=50 openim-server

    - name: Test OpenIM chat
      run: |
        sleep 30
        docker-compose logs --tail=50 openim-chat

    - name: Check the OpenIM environment and status
      id: docker_info
      run: |
        sleep 30
        echo "images<<EOF" >> $GITHUB_ENV
        sudo docker images >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "containers<<EOF" >> $GITHUB_ENV
        sudo docker ps >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          > [!TIP]
          > Run make install to check the status

          ### Docker Images:
          <details><summary>Click to expand docker images</summary>

          ```bash
          ${{ env.images }}
          ```
          </details>

          ### Docker Processes:
          <details><summary>Click to expand docker ps</summary>

          ```bash
          ${{ env.containers }}
          ```
          </details>
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

    - name: stop docker-compose
      run: |
        docker-compose down

    - name: clean all docker containers
      run: |
        docker stop $(docker ps -qa)
        docker rm $(docker ps -qa)
        docker network prune -f
